---
sudo: required
language: python
services:
  - docker
before_install:
  - sudo apt-get -qq update
  - sudo apt install snapd
  - sudo snap install lxd
  - sudo /usr/lib/lxd/lxd-bridge start
  - sudo su travis -c 'lxd init --auto';
  - sudo su travis -c 'lxc network create lxdbr0';
  - sudo su travis -c 'lxc network attach-profile lxdbr0 default eth0';
install:
  - sudo pip install ansible==2.4.2.0
  - sudo pip install testinfra==1.10.1
  - sudo pip install pytest==3.3.0
  - sudo pip install molecule==2.5.0
  - sudo pip install lxc-python2
script:
  - sudo su travis -c 'molecule test'
